"""empty message

Revision ID: e1c201e0a0b8
Revises: 063db99d31e0
Create Date: 2024-12-30 09:59:59.213790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1c201e0a0b8'
down_revision = '063db99d31e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cus_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('cart_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['cus_id'], ['id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_ibfk_1', 'customer', ['customer_id'], ['id'])
        batch_op.drop_column('cus_id')

    # ### end Alembic commands ###
