"""empty message

Revision ID: f008815cec05
Revises: 49790dc58102
Create Date: 2024-12-29 16:29:57.267613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f008815cec05'
down_revision = '49790dc58102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pro_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('new_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pro_picture', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pro_category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'category', ['pro_category_id'], ['category_id'])
        batch_op.drop_column('current_price')
        batch_op.drop_column('product_picture')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('product_picture', mysql.VARCHAR(length=1000), nullable=False))
        batch_op.add_column(sa.Column('current_price', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pro_category_id')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('pro_picture')
        batch_op.drop_column('new_price')
        batch_op.drop_column('pro_name')

    # ### end Alembic commands ###
